### PR TITLE
README / parameter updates

### PR DESCRIPTION
**Pull request by SteveMacenski**
TODO
  - Alex's link
  - Configuration page link (and page) from Nav2 documentation
  - Update Omni demo after anti-twirling behavior is added https://github.com/artofnothingness/mppic/issues/13
  - Defaults after tuned for out of box behavior

We can merge without these, but I'll file a ticket if we merge it so these don't get lost. Feel free to edit the page to add your link of choice to your name

### CODE REVIEW

**Comment by artofnothingness** [comment]
Seems like removing binaries from repo blowed up commits here too...

**Comment by SteveMacenski** [comment]
... I'm not sure what to do about this one. Can we revert that commit  for now and see if you can open a new PR removing the binaries that doesn't have the history issues. In your PR that did that, it also showed a huge git diff so I think something wasn't quite right on that branch

The PR touched 3k lines of code for removing the binaries https://github.com/artofnothingness/mppic/pull/22 so I think something was up with your branch's status. I  think that should be reverted and try again with a new clone with fresh `develop` branch.

**Comment by artofnothingness** [comment]
@SteveMacenski 
Actually i did exactly that. I roll backed this merged PR and then make binaries deletion in develop. There is no this merged PR in history

**Comment by artofnothingness** [comment]
Can you copy readme / params changes to this recreated develop ? I think it removes or recreated commits where binaries was added, that's why all the history changed

**Comment by SteveMacenski** [comment]
I can't tell what I changed, this diff is being blasted by every single line / file. If I try to rebase its just going to conflict again with these conflicts that will be like trying to pick out my changes as a needle in a haystack and I'm likely to miss some. 

Can you please un-do what caused this and leave the gifs in the git history and just delete them at `HEAD`? When clones happen they're not going to pick the gifs up if they were added then removed so we're fixing the core problem of not wanting to download these large files. Going back this far in history might be more "clean" from the perspective of reverting a commit, but its not like we've been all that careful to keep the git history clean with all the merge commits and commit messages. I think its the path of least resistance.

**Comment by artofnothingness** [comment]
I didn't find a way to revert this, even reflog is cleaned up. All changes preserved except this two commits. Can you create new branch and cherry-pick them ?  https://github.com/artofnothingness/mppic/pull/15/commits/0f2d677a97fbbd889d5b114db42b5aa41d927fd1
https://github.com/artofnothingness/mppic/pull/15/commits/c45edbfcd61d6354d93a6eb57b2c5bac32ee2efa

**Comment by artofnothingness** [comment]
> When clones happen they're not going to pick the gifs up if they were added then removed so we're fixing the core problem of not wanting to download these large files. 

didn't they stay in history therefore will be downloaded anyway while git clone ?

**Comment by SteveMacenski** [comment]
OK I'll open a new PR. I have to totally reclone - these changes made even pulling in the `develop` branch on the `develop` branch create massive conflicts. 

> didn't they stay in history therefore will be downloaded anyway while git clone ?

I believe there are simple checks in place if files were added and then removed that it will skip the blob. I haven't run into issues before when swapping out files having the download size return to normal. I can't speak to the method of how it works under the hood, but Git has alot of optimizations.

I will say even after your changes though, the clone size is still 65MB. Probably because its still in the foxy branc

**Pull request closed without merging**
